### ISSUE TITLE
Switch spatial-api to use the new `Dataset.dataset_type` field

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/spatial-api#41]
The `Dataset.data_types` field is being deprecated and at the same time `Dataset.dataset_type` will be required.  In support of this start using/storing the new `dataset_type` field instead of the old `data_types` field.

**Comment by ChuckKollar** [comment]
I'm not sure how to test this on DEV.
MATCH (ds:Dataset) RETURN DISTINCT ds.dataset_types
will return null
MATCH (ds:Dataset) RETURN DISTINCT ds.data_types
will return 68 results.
Apparently the DEV Neo4j (http://18.205.215.12:7474/browser/) has not been updated with this change.

**Comment by ChuckKollar** [comment]
Please see PR: https://github.com/hubmapconsortium/spatial-api/pull/42

Also added additional debug output to chase down differences between results form PROD.
These could be explained by changes to the spatial position of samples, or a bug in postgris,
or a bug in the MS call that maps the sample organ to the body.

NOTE: This also contains changes for PosgreSQL 15 as well as switching to fields in Neo4J that
have been deprecated.
